services:
  microservicio-a:
    build: ./microservicio-a
    ports:
    - 8001:8000
    environment:
      SERVICE_NAME: microservicio-a
      PORT: '8000'
      profiles: '["debug", "release"]'
  microservicio-b:
    build: ./microservicio-b
    ports:
    - 8002:8000
    environment:
      SERVICE_NAME: microservicio-b
      PORT: '8000'
      profiles: '["debug", "release"]'
  microservicio-c:
    build: ./microservicio-c
    ports:
    - 8003:8000
    environment:
      SERVICE_NAME: microservicio-c
      PORT: '8000'
      profiles: '["debug", "release"]'
