name: Registro de imagenes - Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Registrar imagenes usadas
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Descargar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Logging en docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Utilizar mi usuario con minusculas
      id: lowercase
      run: |
        echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Construir y subir microservice-A
      uses: docker/build-push-action@v5
      with:
        context: microservice-A
        push: true
        tags: |
          ghcr.io/${{ steps.lowercase.outputs.repo }}/microservicio-A:latest
          ghcr.io/${{ steps.lowercase.outputs.repo }}/microservicio-A:${{ github.sha }}

    - name: Construir y subir microservice-B
      uses: docker/build-push-action@v5
      with:
        context: microservice-B
        push: true
        tags: |
          ghcr.io/${{ steps.lowercase.outputs.repo }}/microservicio-B:latest
          ghcr.io/${{ steps.lowercase.outputs.repo }}/microservicio-B:${{ github.sha }}

    - name: Construir y subir microservice-C
      uses: docker/build-push-action@v5
      with:
        context: microservice-C
        push: true
        tags: |
          ghcr.io/${{ steps.lowercase.outputs.repo }}/microservicio-C:latest
          ghcr.io/${{ steps.lowercase.outputs.repo }}/microservicio-C:${{ github.sha }}

  cleanup:
    needs: build-and-push
    runs-on: ubuntu-latest
    name: Limpiar estado del pipeline
    if: always()
    steps:
    - name: Limpiar cache de Docker
      run: |
        docker system prune -af --volumes || true

    - name: Limpiar archivos temporales
      run: |
        rm -rf /tmp/* || true
        rm -rf /var/tmp/* || true
        echo "Archivos temporales limpiados"